services:
  tinymediamanager:
    image: ${DOCKER_MIRROR-docker.conversun.com/docker.io/}tinymediamanager/tinymediamanager:${VERSION}
    container_name: tinymediamanager
    ports:
      - "${TRIM_SERVICE_PORT}:4000"
    volumes:
      - ${TRIM_PKGVAR}/config:/config
      - ${MOVIE_DIR:-${TRIM_PKGVAR}/data/movies}:/data/movies
      - ${TVSHOW_DIR:-${TRIM_PKGVAR}/data/tvshows}:/data/tvshows
    environment:
      - TZ=Asia/Shanghai
      - PUID=${TRIM_UID}
      - PGID=${TRIM_GID}
    restart: unless-stopped
