services:
  audiobookshelf:
    image: advplyr/audiobookshelf:${VERSION}
    container_name: audiobookshelf
    ports:
      - "${TRIM_SERVICE_PORT}:80"
    volumes:
      - ${TRIM_PKGVAR}/config:/config
      - ${TRIM_PKGVAR}/metadata:/metadata
      - ${AUDIOBOOK_DIR:-${TRIM_PKGVAR}/audiobooks}:/audiobooks
      - ${PODCAST_DIR:-${TRIM_PKGVAR}/podcasts}:/podcasts
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
