services:
  ani-rss:
    image: wushuo894/ani-rss:v${VERSION}
    container_name: ani-rss
    ports:
      - "${TRIM_SERVICE_PORT}:7789"
    volumes:
      - ${TRIM_PKGVAR}/config:/config
      - ${DOWNLOAD_DIR:-${TRIM_PKGVAR}/downloads}:/downloads
    environment:
      - TZ=Asia/Shanghai
      - PUID=${TRIM_UID}
      - PGID=${TRIM_GID}
    restart: unless-stopped
